name: Go Build and Test
on: [push]
jobs:

  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: [1.15, 1.16, 1.17, 1.18, 1.19, "1.20", 1.21]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Get dependencies
      run: go mod download

    - name: Build
      run: go build -v .

    - name: Test
      run: go test ./...

    - name: Race
      run: go test -race -count 10 ./...
